name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Build React
        run: |
          yarn --cwd ./web install
          yarn --cwd ./web build

      - name: Build Go
        run: |
          make easy-gate
