name: Coverage

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Coverage
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
