name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v3
        
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          
      - name: Build Frontend
        run: |
          yarn --cwd ./web install
          yarn --cwd ./web build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
